import type { NextPage } from "next";
import Head from "next/head";
import { KeyVisual } from "../src/components/top/KeyVisual";
import { OpeningPage } from "../src/components/top/OpeningPage";

const Home: NextPage = () => {
  return (
    <div className=" h-full">
      <Head>
        <title>UWear公式サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon/favicon_head.png" />
      </Head>
      <OpeningPage />
      <KeyVisual />
    </div>
  );
};

export default Home;
