import type { NextPage } from "next";
import Head from "next/head";
import { InitialPage } from "../src/components/InitialPage";

const Home: NextPage = () => {
  return (
    <div className="bg-clay h-full">
      <Head>
        <title>UWear公式サイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon/favicon_head.png" />
      </Head>
      <InitialPage />
    </div>
  );
};

export default Home;
